Gke build (WIP)
CodeNow/docker-listener pull request #175
Opened 2017-03-09 19:04 UTC by anandkumarpatel

2017-03-16 01:03 UTC, podviaznikov requested changes

2017-03-16 01:03 UTC, podviaznikov commented on lib/workers/docker.event.publish.js
> +    docker.getImage(job.Actor.Attributes.dockerTag).inspect(cb)
I don't think `Actor` and `Attributes` are required

2017-03-16 01:03 UTC, podviaznikov commented on test/unit/worker/docker.event.publish.js
> +      DockerClient.prototype.inspectContainerAsync.returns(Promise.resolve())
you can import `sinon-as-promised` and just do `DockerClient.prototype.inspectContainerAsync.resolves()`

2017-03-21 00:23 UTC, anandkumarpatel commented on lib/workers/docker.event.publish.js
> +    docker.getImage(job.Actor.Attributes.dockerTag).inspect(cb)
they are based on type

2017-03-22 01:48 UTC, anandkumarpatel commented on test/unit/worker/docker.event.publish.js
> +      DockerClient.prototype.inspectContainerAsync.returns(Promise.resolve())
done

2017-03-22 01:50 UTC, podviaznikov approved these changes

2017-03-22 01:50 UTC, podviaznikov commented on lib/workers/docker.event.publish.js
> +    Cmd: Joi.alternatives().try(Joi.array().items(Joi.string()), null),
can't you just say `Joi.array().items(Joi.string())`? is it not the same as alternative between something and `null`?

2017-03-22 01:53 UTC, anandkumarpatel commented on lib/workers/docker.event.publish.js
> +    Cmd: Joi.alternatives().try(Joi.array().items(Joi.string()), null),
no, sadly null is a value.

2017-03-22 19:40 UTC, merged